import type { ChapterItem } from '../courseProgress'

export const COURSE_CHAPTERS: Record<string, Array<Omit<ChapterItem, 'status'>>> = {
  python: [
    {
      num: '01',
      title: 'Python Setup & Syntax Fundamentals',
      subtitle: 'Chapter 01: Setup & Variables',
      description: 'Learn variables, console output, primitive data types, and the Zen of Python.',
      xp: 250,
      lessonId: 'python-ch1-lesson1',
    },
    {
      num: '02',
      title: 'Variables, Strings & Number Operations',
      subtitle: 'Chapter 02: Operations & Expressions',
      description: 'Master arithmetic operations, string concatenation, f-strings, and type casting.',
      xp: 350,
      lessonId: 'python-ch2-lesson1',
    },
    {
      num: '03',
      title: 'Conditionals, Boolean Logic & Decisions',
      subtitle: 'Chapter 03: Decision Gates',
      description: 'Control flow with if-elif-else statements and logical operators.',
      xp: 400,
      lessonId: 'python-ch3-lesson1',
    },
    {
      num: '04',
      title: 'Loops & Iteration',
      subtitle: 'Chapter 04: The Cycle of Logic',
      description: 'Automate tasks with while loops, for loops, and sequence iteration.',
      xp: 450,
      lessonId: 'python-ch4-lesson1',
    },
  ],
  javascript: [
    {
      num: '01',
      title: 'JavaScript Fundamentals',
      subtitle: 'Chapter 01: The Web Language',
      description: 'Learn var, let, const, data types, and basic operators.',
      xp: 250,
      lessonId: 'js-ch1-lesson1',
    },
    {
      num: '02',
      title: 'Functions & Scope',
      subtitle: 'Chapter 02: Reusable Blocks',
      description: 'Master arrow functions, closures, and lexical scope.',
      xp: 350,
      lessonId: 'js-ch2-lesson1',
    },
    {
      num: '03',
      title: 'Arrays & Objects',
      subtitle: 'Chapter 03: Data Structures',
      description: 'Map, filter, reduce, and object destructuring.',
      xp: 400,
      lessonId: 'js-ch3-lesson1',
    },
  ],
  'html-css': [
    {
      num: '01',
      title: 'HTML Structure & Semantics',
      subtitle: 'Chapter 01: The Skeleton',
      description: 'Learn elements, attributes, semantic tags, and forms.',
      xp: 250,
      lessonId: 'html-ch1-lesson1',
    },
    {
      num: '02',
      title: 'CSS Styling Basics',
      subtitle: 'Chapter 02: Painting the Web',
      description: 'Master selectors, colors, fonts, and the box model.',
      xp: 350,
      lessonId: 'html-ch2-lesson1',
    },
    {
      num: '03',
      title: 'Flexbox & Grid Layouts',
      subtitle: 'Chapter 03: Page Layouts',
      description: 'Build responsive designs with modern CSS layout modules.',
      xp: 400,
      lessonId: 'html-ch3-lesson1',
    },
  ],
  sql: [
    {
      num: '01',
      title: 'Database Fundamentals & Queries',
      subtitle: 'Chapter 01: Data Retrieval',
      description: 'Learn SELECT, FROM, WHERE, and sorting results.',
      xp: 250,
      lessonId: 'sql-ch1-lesson1',
    },
    {
      num: '02',
      title: 'Joins & Relationships',
      subtitle: 'Chapter 02: Connecting Data',
      description: 'Master INNER, LEFT, RIGHT, and FULL joins across tables.',
      xp: 350,
      lessonId: 'sql-ch2-lesson1',
    },
  ],
  react: [
    {
      num: '01',
      title: 'Components & JSX',
      subtitle: 'Chapter 01: The UI Building Blocks',
      description: 'Learn functional components, props, and JSX syntax.',
      xp: 250,
      lessonId: 'react-ch1-lesson1',
    },
    {
      num: '02',
      title: 'State & Effects',
      subtitle: 'Chapter 02: Component Lifecycles',
      description: 'Master useState, useEffect, and reactivity.',
      xp: 350,
      lessonId: 'react-ch2-lesson1',
    },
  ],
}